# Generated by Django 4.1 on 2022-08-19 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_orderitem_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='start_date',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_date',
        ),
    ]
